## YAML Template.
---
management:
#    security:
#        enabled: false
        
        
security:
    jwt:
        secret-key : 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
        expiration-time: 3600000
 
#    basic:
#        enabled: false
        
        
 
spring:
    main:
        allow-bean-definition-overriding: true
    profiles:
      active: prod,javamelody
  
    data:
      auditing:
        auditor-aware-ref: auditorProvider
    output:
        ansi:
            enabled: DETECT
    application:
        name: Comptabilite-core
    batch:
        job:
            enabled: false        
 
    jmx.enabled: true
    devtools:
        add-properties:
            false
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        url: jdbc:sqlserver://localhost\sql2019;database=GComptabilite;integratedSecurity=false;encrypt=false;trustServerCertificate=true
        username: sa
        password: 123 

        
    jpa:
        defer-datasource-initialization : true
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        database: SQL_SERVER
        show-sql: false
        generate-ddl: true
        hibernate:
            ddl-auto: update
            use_sql_comments : true
            show-sql: true
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate.default_schema: Comptabilite
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            org.hibernate.envers.store_data_at_delete: true
 
#                   
    messages:
        basename: i18n/messages
        
server:
    port: 9090
    contextPath: /parametrage-core
    error:
        include-stacktrace: ON_PARAM